-- User Table
CREATE TABLE IF NOT EXISTS user(
	uid INTEGER PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(100) NOT NULL UNIQUE,
	passh CHAR(128) NOT NULL,
	namef VARCHAR(35) NOT NULL,
	namel VARCHAR(35) NOT NULL
);